import { useState } from 'react';
import { CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../api/client.js';
import { useCart } from '../context/CartContext.jsx';
import { useAuth } from '../context/AuthContext.jsx';

const price = (value) => `৳ ${Number(value).toLocaleString('en-US')}`;

export default function Checkout() {
  const { items, total, clearCart } = useCart(); const { user } = useAuth();
  const [form, setForm] = useState({ name: user?.name || '', phone: user?.phone || '', area: user?.address?.area || '', city: user?.address?.city || 'ঢাকা', district: user?.address?.district || '', details: '', paymentMethod: 'cash_on_delivery' });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [complete, setComplete] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function submit(event) { event.preventDefault(); if (!items.length) return; try { setLoading(true); setError(''); await api.post('/orders', { items: items.map((item) => ({ product: item._id, qty: item.qty })), paymentMethod: form.paymentMethod, deliveryAddress: form }); clearCart(); setComplete(true); } catch (err) { setError(err.response?.data?.message || 'অর্ডার পাঠানো যায়নি।'); } finally { setLoading(false); } }
  if (complete) return <main className="page-container section-space"><div className="mx-auto max-w-lg rounded-2xl bg-white p-10 text-center shadow-card"><CheckCircle2 className="mx-auto text-green-600" size={64} /><h1 className="mt-4 text-2xl font-bold text-green-900">অর্ডার সফল হয়েছে!</h1><p className="mt-2 text-zinc-600">আমরা খুব শীঘ্রই আপনার সাথে যোগাযোগ করব।</p><Link className="btn-primary mt-6" to="/shop">আরও পণ্য দেখুন</Link></div></main>;
  if (!items.length) return <main className="page-container section-space text-center"><h1 className="section-heading">আপনার কার্ট খালি</h1><Link className="btn-primary mt-4" to="/shop">শপে যান</Link></main>;
  return <main className="page-container section-space"><h1 className="section-heading">অর্ডার সম্পন্ন করুন</h1><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_370px]"><form onSubmit={submit} className="rounded-xl bg-white p-6 shadow-card"><h2 className="text-xl font-bold">ডেলিভারির তথ্য</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{[['name', 'প্রাপকের নাম'], ['phone', 'মোবাইল নম্বর'], ['area', 'এলাকা'], ['city', 'শহর'], ['district', 'জেলা']].map(([name, label]) => <label className="text-sm font-semibold" key={name}>{label}<input required name={name} value={form[name]} onChange={update} className="mt-1 w-full rounded-lg border px-3 py-2 outline-none focus:border-primary" /></label>)}</div><label className="mt-4 block text-sm font-semibold">বিস্তারিত ঠিকানা<textarea name="details" value={form.details} onChange={update} className="mt-1 w-full rounded-lg border px-3 py-2 outline-none focus:border-primary" rows="3" /></label><fieldset className="mt-5"><legend className="font-bold">পেমেন্ট পদ্ধতি</legend><div className="mt-2 flex flex-wrap gap-4 text-sm">{[['cash_on_delivery', 'ক্যাশ অন ডেলিভারি'], ['bkash', 'বিকাশ'], ['sslcommerz', 'কার্ড / SSL Commerz']].map(([value, label]) => <label key={value}><input type="radio" name="paymentMethod" value={value} checked={form.paymentMethod === value} onChange={update} /> {label}</label>)}</div></fieldset>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={loading} className="btn-primary mt-6 w-full">{loading ? 'অর্ডার পাঠানো হচ্ছে...' : 'অর্ডার নিশ্চিত করুন'}</button></form><aside className="h-fit rounded-xl bg-white p-6 shadow-card"><h2 className="text-xl font-bold">অর্ডার সামারি</h2><div className="mt-4 space-y-3">{items.map((item) => <div className="flex justify-between gap-3 text-sm" key={item._id}><span className="line-clamp-1">{item.banglaName || item.name} × {item.qty}</span><b>{price(item.price * item.qty)}</b></div>)}</div><div className="mt-5 flex justify-between border-t pt-4 text-lg font-bold"><span>মোট</span><span>{price(total)}</span></div></aside></div></main>;
}
