import { Minus, Plus, ShoppingBag, ShoppingCart, Trash2, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useCart } from '../context/CartContext.jsx';

const price = (value) => `৳ ${Number(value).toLocaleString('en-US')}`;

export default function Cart({ open, onClose }) {
  const { items, total, updateQty, removeItem } = useCart();
  if (!open) return null;
  return <div className="fixed inset-0 z-50 bg-black/40" onMouseDown={onClose}><aside onMouseDown={(event) => event.stopPropagation()} className="ml-auto flex h-full w-full max-w-sm flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><ShoppingCart className="text-yellow-700" />আপনার কার্ট</h2><button className="rounded-full p-2 hover:bg-zinc-100" onClick={onClose} aria-label="কার্ট বন্ধ করুন"><X size={21} /></button></div><div className="flex-1 overflow-y-auto p-4">{items.length ? items.map((item) => <article className="flex gap-3 border-b py-3" key={item._id}><img className="h-16 w-16 rounded-lg object-cover" src={item.images?.[0]} alt="" /><div className="min-w-0 flex-1"><h3 className="line-clamp-2 text-sm font-bold">{item.banglaName || item.name}</h3><p className="text-sm font-bold text-primary">{price(item.price)}</p><div className="mt-1 flex items-center gap-2"><button className="rounded border p-1 text-primary" onClick={() => updateQty(item._id, item.qty - 1)} aria-label="কম করুন"><Minus size={14} /></button><span className="w-5 text-center text-sm font-bold">{item.qty}</span><button className="rounded border p-1 text-primary" onClick={() => updateQty(item._id, item.qty + 1)} aria-label="বাড়ান"><Plus size={14} /></button></div></div><button onClick={() => removeItem(item._id)} className="self-start p-1 text-red-500" aria-label="মুছুন"><Trash2 size={17} /></button></article>) : <div className="mt-16 text-center text-zinc-500"><ShoppingBag className="mx-auto mb-3" size={46} /><p>আপনার কার্ট এখন খালি।</p></div>}</div><div className="border-t bg-zinc-50 p-5"><div className="mb-3 flex justify-between text-lg font-bold"><span>সর্বমোট</span><span>{price(total)}</span></div>{items.length ? <Link onClick={onClose} to="/checkout" className="btn-secondary w-full">অর্ডার করুন</Link> : <button disabled className="btn-secondary w-full">অর্ডার করুন</button>}</div></aside></div>;
}
