import { useEffect, useState } from 'react';
import { ArrowRight, Check, CheckCircle2, HeartHandshake, MessageSquareHeart, PawPrint, ShieldCheck, Star, Stethoscope } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext.jsx';

const slides = [
  { image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1100&q=85', eyebrowBn: 'প্রিমিয়াম পেট নিউট্রিশন', eyebrowEn: 'PREMIUM PET NUTRITION', titleBn: 'ভালোবাসার সঠিক খাবার, প্রতিদিন।', titleEn: 'The right food for every day of love.', textBn: 'বয়স ও প্রয়োজন অনুযায়ী বিশ্বস্ত ব্র্যান্ডের পেট ফুড বেছে নিন।', textEn: 'Choose trusted pet food tailored to your companion’s age and needs.', to: '/shop', labelBn: 'অরিজিনাল পণ্য ও দ্রুত ডেলিভারি', labelEn: 'Original products, fast delivery' },
  { image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1100&q=85', eyebrowBn: 'ক্যাট কেয়ার কালেকশন', eyebrowEn: 'CAT CARE COLLECTION', titleBn: 'আপনার বিড়ালের জন্য, শুধু সেরাটুকুই।', titleEn: 'Only the best for your cat.', textBn: 'খাবার, খেলনা, লিটার ও প্রয়োজনীয় কেয়ার—সব এক জায়গায়।', textEn: 'Food, toys, litter and everyday care—together in one place.', to: '/shop?category=cat', labelBn: 'ক্যাট প্যারেন্টদের বিশ্বস্ত পছন্দ', labelEn: 'Trusted by cat parents' },
  { image: 'https://images.unsplash.com/photo-1601758123927-196c88c39b3a?auto=format&fit=crop&w=1100&q=85', eyebrowBn: 'ভেটেরিনারি কেয়ার', eyebrowEn: 'VETERINARY CARE', titleBn: 'প্রয়োজনে, বিশেষজ্ঞ সবসময় পাশে।', titleEn: 'Expert support when it matters.', textBn: 'প্রাণীর অসুস্থতা বা যত্ন নিয়ে ভেট টিমের সাথে কথা বলুন।', textEn: 'Talk to a vet team about your companion’s health and care.', to: '/consultation', labelBn: 'প্রাথমিক পরামর্শ বিনামূল্যে', labelEn: 'Free initial advice' }
];

export default function HeroBanner() {
  const [active, setActive] = useState(0); const { language, t } = useLanguage();
  useEffect(() => { const timer = setInterval(() => setActive((current) => (current + 1) % slides.length), 5500); return () => clearInterval(timer); }, []);
  const slide = slides[active]; const title = language === 'bn' ? slide.titleBn : slide.titleEn; const text = language === 'bn' ? slide.textBn : slide.textEn; const eyebrow = language === 'bn' ? slide.eyebrowBn : slide.eyebrowEn;
  return <section className="hero-world relative overflow-hidden"><div className="hero-grid absolute inset-0 opacity-50" /><div className="hero-glow hero-glow-one" /><div className="hero-glow hero-glow-two" /><div className="page-container relative z-10 grid min-h-[530px] items-center gap-8 py-12 lg:grid-cols-[1.05fr_.95fr] lg:py-14"><div className="max-w-2xl"><div className="flex flex-wrap items-center gap-2"><div className="hero-chip"><Star size={14} className="text-yellow-600" fill="currentColor" />{eyebrow}</div><Link to="/consultation" className="inline-flex items-center gap-1.5 rounded-full bg-green-600 px-3.5 py-1.5 text-xs font-bold text-white shadow-sm transition hover:bg-green-700"><MessageSquareHeart size={13} />{language === 'bn' ? '১০০% ফ্রি ভেট চ্যাট' : '100% free vet chat'}</Link></div><h1 className="mt-6 max-w-xl text-4xl font-bold leading-[1.08] tracking-tight text-zinc-900 sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-5 max-w-xl text-base leading-7 text-zinc-600 sm:text-lg">{text}</p><div className="mt-8 flex flex-wrap gap-3"><Link className="hero-cta" to={slide.to}>{slide.to === '/consultation' ? t('freeConsultation') : t('shopNow')} <ArrowRight size={18} /></Link><Link className="hero-ghost" to="/consultation"><Stethoscope size={18} />{language === 'bn' ? 'ফ্রি ভেট চ্যাট' : 'Free vet chat'}</Link></div><div className="mt-9 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-zinc-600">{[[ShieldCheck, language === 'bn' ? '১০০% অরিজিনাল' : '100% original'], [Check, language === 'bn' ? 'নিরাপদ পেমেন্ট' : 'Secure payment'], [HeartHandshake, language === 'bn' ? 'বিশেষজ্ঞ কেয়ার' : 'Expert care']].map(([Icon, item]) => <span className="flex items-center gap-1.5" key={item}><Icon size={15} className="text-[#b98200]" />{item}</span>)}</div></div><HeroScene slide={slide} language={language} /><div className="absolute bottom-7 left-1/2 flex -translate-x-1/2 gap-2 lg:left-auto lg:right-0 lg:translate-x-0">{slides.map((_item, index) => <button key={index} onClick={() => setActive(index)} className={`h-2.5 rounded-full transition-all ${index === active ? 'w-9 bg-[#d39b00]' : 'w-2.5 bg-zinc-300 hover:bg-zinc-400'}`} aria-label={`Slide ${index + 1}`} />)}</div></div></section>;
}

function HeroScene({ slide, language }) { return <div className="hero-stage mx-auto w-full max-w-lg"><div className="hero-orbit hero-orbit-1"><span>●</span><span>●</span></div><div className="hero-orbit hero-orbit-2"><span>+</span><span>+</span></div><div className="hero-platform hero-platform-shadow" /><div className="hero-platform hero-platform-top" /><div className="hero-photo-frame"><img src={slide.image} alt="Happy pet with care products" /><span className="hero-photo-label">{language === 'bn' ? slide.labelBn : slide.labelEn}</span></div><div className="hero-food-pack bg-gradient-to-br from-yellow-100 to-[#f4c52a]"><PawPrint size={32} /><span className="mt-1 text-[10px] font-black tracking-[.2em] text-zinc-800">PETCARE</span><span className="text-[8px] font-bold text-zinc-700">NOURISH</span></div><div className="hero-float-card hero-float-card-top"><span className="grid h-8 w-8 place-items-center rounded-lg bg-yellow-100 text-yellow-700"><Star size={15} fill="currentColor" /></span><span><b>4.9/5</b><small>{language === 'bn' ? 'পেট প্যারেন্ট রেটিং' : 'Pet parent rating'}</small></span></div><div className="hero-float-card hero-float-card-bottom"><span className="grid h-8 w-8 place-items-center rounded-lg bg-yellow-100 text-yellow-700"><CheckCircle2 size={16} /></span><span><b>{language === 'bn' ? 'ভেরিফাইড প্রোডাক্ট' : 'Verified products'}</b><small>{language === 'bn' ? 'বিশ্বস্ত ব্র্যান্ড' : 'Trusted brands'}</small></span></div></div>; }
